## Configuration file

name: reify
url: http://reifycode.github.io

author: 
- Shreyash Patodia
- Pulkit Agarwal
- Yash Karnawat
description: We are a group of Computer Science enthusiasts looking to find our way in the world of Computer Science.

title: reify

permalink: /:year/:month/:day/:title.html
markdown: kramdown

gems:
  - jekyll-redirect-from

defaults:
    scope:
      path: _posts
    values:
      lang: en
      layout: default


nodes:
- text: Github
  url: https://github.com/reifycode


