## Configuration file

name: reify
url: http://reifycode.github.io

author: 
- Shreyash Patodia
- Pulkit Agarwal
- Yash Karnawat
description: Open web enth
title: reify

permalink: /:year/:month/:day/:title.html
markdown: kramdown

gems:
  - jekyll-redirect-from

defaults:
    scope:
      path: _posts/en
    values:
      lang: en
      layout: default


nodes:
- text: Github
  url: https://github.com/reifycode


